//WARNING!!!!
// DO NOT CHANGE UNTILL YOU KNOW WHAT YOU ARE DOING!!!
//TAK

const modelConstants = {
    TXN_TYPES_ARRAY: ['WALLET_TOPUP', 'TRANSFER', 'REFUND', 'ORDER', 'COUPON_BUY',
        'FIAT_TO_CRYPTO_EXCHANGE', 'CRYPTO_TO_FIAT_EXCHANGE', 'REWARD_TO_KRW', 'USER_AD_POST'
    ],
    TXN_STATUS_ARRAY: ['PENDING', 'CANCELLED', 'CONFIRMED', 'CANCELLED_BY_USER'],
    REWARD_TXN_TYPES_ARRAY: ['REWARD_TO_KRW'],
}
module.exports = {
    modelConstants,
};